// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH7gc0SRmkz5XExrc0ZQ_MZcacJ0AWm84',
    appId: '1:957647225907:web:352224f2c131416fb80f46',
    messagingSenderId: '957647225907',
    projectId: 'trip-manager-83bca',
    authDomain: 'trip-manager-83bca.firebaseapp.com',
    storageBucket: 'trip-manager-83bca.appspot.com',
    measurementId: 'G-BSD2P6ZKM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevwuErAN9LBDc4naEoO34jU0dOfyTAJk',
    appId: '1:957647225907:android:47070f708445f5a2b80f46',
    messagingSenderId: '957647225907',
    projectId: 'trip-manager-83bca',
    storageBucket: 'trip-manager-83bca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz8UNXnpYYvLHjGODe4LNjlG5Y9cbavEE',
    appId: '1:957647225907:ios:60d928608e9fcd63b80f46',
    messagingSenderId: '957647225907',
    projectId: 'trip-manager-83bca',
    storageBucket: 'trip-manager-83bca.appspot.com',
    iosBundleId: 'com.example.tripmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz8UNXnpYYvLHjGODe4LNjlG5Y9cbavEE',
    appId: '1:957647225907:ios:60d928608e9fcd63b80f46',
    messagingSenderId: '957647225907',
    projectId: 'trip-manager-83bca',
    storageBucket: 'trip-manager-83bca.appspot.com',
    iosBundleId: 'com.example.tripmanager',
  );
}
